**Import necessary libraries**

In [424]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score

**Load the dataset**

In [426]:
data = pd.read_csv("Customer-Churn-Records.csv")
data

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  Complain  Satisfaction Score Card Type  \
0           101348.88       1         1                   2   DIAMOND   
1           112542.58       0         1                   3   DIAMOND   
2           113931.57       1         1                   3   DIAMOND   
3            93826.63       0         0                   5      GOLD   
4            79084.10       0         0                   5      GOLD   
...               ...     ...       ...                 ...       ...   
9995         96270.64       0         0                   1   DIAMOND   
9996        101699.77       0         0                   5  PLATINUM   
9997         42085.58       1         1                   3    SILVER   
9998         92888.52       1         1                   2      GOLD   
9999         38190.78       0         0                   3   DIAMOND   

      Point Earned  
0              464  
1              456  
2              377  
3              350  
4              425  
...            ...  
9995           300  
9996           771  
9997           564  
9998           339  
9999           911  

[10000 rows x 18 columns]

**Data Inspection**

In [428]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   RowNumber           10000 non-null  int64  
 1   CustomerId          10000 non-null  int64  
 2   Surname             10000 non-null  object 
 3   CreditScore         10000 non-null  int64  
 4   Geography           10000 non-null  object 
 5   Gender              10000 non-null  object 
 6   Age                 10000 non-null  int64  
 7   Tenure              10000 non-null  int64  
 8   Balance             10000 non-null  float64
 9   NumOfProducts       10000 non-null  int64  
 10  HasCrCard           10000 non-null  int64  
 11  IsActiveMember      10000 non-null  int64  
 12  EstimatedSalary     10000 non-null  float64
 13  Exited              10000 non-null  int64  
 14  Complain            10000 non-null  int64  
 15  Satisfaction Score  10000 non-null  int64  
 16  Card 

In [429]:
data.shape

(10000, 18)

In [430]:
data.dtypes

RowNumber               int64
CustomerId              int64
Surname                object
CreditScore             int64
Geography              object
Gender                 object
Age                     int64
Tenure                  int64
Balance               float64
NumOfProducts           int64
HasCrCard               int64
IsActiveMember          int64
EstimatedSalary       float64
Exited                  int64
Complain                int64
Satisfaction Score      int64
Card Type              object
Point Earned            int64
dtype: object

In [431]:
data.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited      Complain  Satisfaction Score  \
count     10000.000000  10000.000000  10000.000000        10000.000000   
mean     100090.239881      0.203800      0.204400            3.013800   
std       57510.492818      0.402842      0.403283            1.405919   
min          11.580000      0.000000      0.000000            1.000000   
25%       51002.110000      0.000000      0.000000            2.000000   
50%      100193.915000      0.000000      0.000000            3.000000   
75%      149388.247500      0.000000      0.000000            4.000000   
max      199992.480000      1.000000      1.000000            5.000000   

       Point Earned  
count  10000.000000  
mean     606.515100  
std      225.924839  
min      119.000000  
25%      410.000000  
50%      605.000000  
75%      801.000000  
max     1000.000000

**Data cleaning**

In [433]:
data.isnull().sum()

RowNumber             0
CustomerId            0
Surname               0
CreditScore           0
Geography             0
Gender                0
Age                   0
Tenure                0
Balance               0
NumOfProducts         0
HasCrCard             0
IsActiveMember        0
EstimatedSalary       0
Exited                0
Complain              0
Satisfaction Score    0
Card Type             0
Point Earned          0
dtype: int64

In [434]:
data.duplicated().sum()

0

**Data Transformation**

In [436]:
data["Gender"].unique()

array(['Female', 'Male'], dtype=object)

In [437]:
data['Gender'].replace(['Male', 'Female'], [1,2], inplace=True)

In [438]:
data["Card Type"].unique()

array(['DIAMOND', 'GOLD', 'SILVER', 'PLATINUM'], dtype=object)

In [439]:
data['Card Type'].replace(['SILVER', 'GOLD', 'PLATINUM', 'DIAMOND'], [1,2,3,4], inplace=True)

In [440]:
data.drop(columns = ['CustomerId', 'Surname', 'Geography', 'RowNumber'], inplace = True)

In [441]:
data.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       2   42       2       0.00              1          1   
1          608       2   41       1   83807.86              1          0   
2          502       2   42       8  159660.80              3          1   
3          699       2   39       1       0.00              2          0   
4          850       2   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Complain  Satisfaction Score  \
0               1        101348.88       1         1                   2   
1               1        112542.58       0         1                   3   
2               0        113931.57       1         1                   3   
3               0         93826.63       0         0                   5   
4               1         79084.10       0         0                   5   

   Card Type  Point Earned  
0          4           464  
1          4           456  
2          4           377  
3          2           350  
4          2           425

In [442]:
data['Exited'].value_counts()

Exited
0    7962
1    2038
Name: count, dtype: int64

**The dataset is unbalaced**

**0 -> Exit**

**1 -> NotExit**

In [446]:
data.groupby('Exited').mean()

CreditScore    Gender        Age    Tenure       Balance  \
Exited                                                             
0        651.837855  1.427531  37.408063  5.032781  72742.750663   
1        645.414622  1.558881  44.835623  4.934740  91109.476006   

        NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Complain  \
Exited                                                                        
0            1.544210   0.707109        0.554635     99726.853141  0.001256   
1            1.475466   0.699215        0.360648    101509.908783  0.998037   

        Satisfaction Score  Card Type  Point Earned  
Exited                                               
0                 3.017960   2.491711    607.044084  
1                 2.997547   2.538763    604.448479

**Balance the data since it had higher number for Customers who exited than those who did not exit. Balanced data trains the model well ensuring accurate predictions**

In [448]:
Exit = data[data.Exited == 0]
NotExit = data[data.Exited == 1]

In [449]:
print(Exit.shape)
print(NotExit.shape)

(7962, 14)
(2038, 14)


In [450]:
Exit_sample = Exit.sample(n = 2038)

In [451]:
Exit_sample.shape

(2038, 14)

In [452]:
new_data = pd.concat([Exit_sample, NotExit], axis=0)

In [453]:
new_data.shape

(4076, 14)

In [454]:
new_data.to_csv("Customer churn.csv", index = False)

In [455]:
new_data

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
3287          693       1   37       1       0.00              2          1   
5284          745       1   51       3   99183.90              1          1   
3423          493       1   32       8   46161.18              1          1   
6484          719       1   44       2       0.00              2          1   
3584          506       1   28       8   53053.76              1          0   
...           ...     ...  ...     ...        ...            ...        ...   
9981          498       1   42       3  152039.70              1          1   
9982          655       2   46       7  137145.12              1          1   
9991          597       2   53       4   88381.21              1          1   
9997          709       2   36       7       0.00              1          0   
9998          772       1   42       3   75075.31              2          1   

      IsActiveMember  EstimatedSalary  Exited  Complain  Satisfaction Score  \
3287               1         82867.55       0         0                   1   
5284               1         28922.25       0         0                   5   
3423               1         79577.40       0         0                   2   
6484               0        196582.19       0         0                   5   
3584               1         24577.34       0         0                   3   
...              ...              ...     ...       ...                 ...   
9981               1         53445.17       1         1                   3   
9982               0        115146.40       1         1                   4   
9991               0         69384.71       1         1                   3   
9997               1         42085.58       1         1                   3   
9998               0         92888.52       1         1                   2   

      Card Type  Point Earned  
3287          4           502  
5284          1           270  
3423          2           606  
6484          2           660  
3584          2           340  
...         ...           ...  
9981          2           790  
9982          2           591  
9991          2           369  
9997          1           564  
9998          2           339  

[4076 rows x 14 columns]

**Transforming the newly created dataset**

In [457]:
new_data["Gender"].unique()

array([1, 2], dtype=int64)

In [458]:
new_data['Gender'].replace(['Male', 'Female'], [1,2], inplace=True)

In [459]:
new_data["Card Type"].unique()

array([4, 1, 2, 3], dtype=int64)

In [460]:
new_data['Card Type'].replace(['SILVER', 'GOLD', 'PLATINUM', 'DIAMOND'], [1,2,3,4], inplace=True)

In [461]:
new_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4076 entries, 3287 to 9998
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   CreditScore         4076 non-null   int64  
 1   Gender              4076 non-null   int64  
 2   Age                 4076 non-null   int64  
 3   Tenure              4076 non-null   int64  
 4   Balance             4076 non-null   float64
 5   NumOfProducts       4076 non-null   int64  
 6   HasCrCard           4076 non-null   int64  
 7   IsActiveMember      4076 non-null   int64  
 8   EstimatedSalary     4076 non-null   float64
 9   Exited              4076 non-null   int64  
 10  Complain            4076 non-null   int64  
 11  Satisfaction Score  4076 non-null   int64  
 12  Card Type           4076 non-null   int64  
 13  Point Earned        4076 non-null   int64  
dtypes: float64(2), int64(12)
memory usage: 477.7 KB


In [462]:
new_data.groupby('Exited').mean()

CreditScore    Gender        Age   Tenure       Balance  \
Exited                                                            
0        651.732090  1.436212  37.428361  5.05103  73751.675339   
1        645.414622  1.558881  44.835623  4.93474  91109.476006   

        NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Complain  \
Exited                                                                        
0            1.534347   0.706084        0.567713    100125.201389  0.001472   
1            1.475466   0.699215        0.360648    101509.908783  0.998037   

        Satisfaction Score  Card Type  Point Earned  
Exited                                               
0                 2.985770   2.460746    607.303238  
1                 2.997547   2.538763    604.448479

In [463]:
new_data

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
3287          693       1   37       1       0.00              2          1   
5284          745       1   51       3   99183.90              1          1   
3423          493       1   32       8   46161.18              1          1   
6484          719       1   44       2       0.00              2          1   
3584          506       1   28       8   53053.76              1          0   
...           ...     ...  ...     ...        ...            ...        ...   
9981          498       1   42       3  152039.70              1          1   
9982          655       2   46       7  137145.12              1          1   
9991          597       2   53       4   88381.21              1          1   
9997          709       2   36       7       0.00              1          0   
9998          772       1   42       3   75075.31              2          1   

      IsActiveMember  EstimatedSalary  Exited  Complain  Satisfaction Score  \
3287               1         82867.55       0         0                   1   
5284               1         28922.25       0         0                   5   
3423               1         79577.40       0         0                   2   
6484               0        196582.19       0         0                   5   
3584               1         24577.34       0         0                   3   
...              ...              ...     ...       ...                 ...   
9981               1         53445.17       1         1                   3   
9982               0        115146.40       1         1                   4   
9991               0         69384.71       1         1                   3   
9997               1         42085.58       1         1                   3   
9998               0         92888.52       1         1                   2   

      Card Type  Point Earned  
3287          4           502  
5284          1           270  
3423          2           606  
6484          2           660  
3584          2           340  
...         ...           ...  
9981          2           790  
9982          2           591  
9991          2           369  
9997          1           564  
9998          2           339  

[4076 rows x 14 columns]

**Splliting Data**

In [465]:
x = new_data.drop(columns = ['Exited'], axis=1)
y = new_data['Exited']

In [466]:
x

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
3287          693       1   37       1       0.00              2          1   
5284          745       1   51       3   99183.90              1          1   
3423          493       1   32       8   46161.18              1          1   
6484          719       1   44       2       0.00              2          1   
3584          506       1   28       8   53053.76              1          0   
...           ...     ...  ...     ...        ...            ...        ...   
9981          498       1   42       3  152039.70              1          1   
9982          655       2   46       7  137145.12              1          1   
9991          597       2   53       4   88381.21              1          1   
9997          709       2   36       7       0.00              1          0   
9998          772       1   42       3   75075.31              2          1   

      IsActiveMember  EstimatedSalary  Complain  Satisfaction Score  \
3287               1         82867.55         0                   1   
5284               1         28922.25         0                   5   
3423               1         79577.40         0                   2   
6484               0        196582.19         0                   5   
3584               1         24577.34         0                   3   
...              ...              ...       ...                 ...   
9981               1         53445.17         1                   3   
9982               0        115146.40         1                   4   
9991               0         69384.71         1                   3   
9997               1         42085.58         1                   3   
9998               0         92888.52         1                   2   

      Card Type  Point Earned  
3287          4           502  
5284          1           270  
3423          2           606  
6484          2           660  
3584          2           340  
...         ...           ...  
9981          2           790  
9982          2           591  
9991          2           369  
9997          1           564  
9998          2           339  

[4076 rows x 13 columns]

In [467]:
y

3287    0
5284    0
3423    0
6484    0
3584    0
       ..
9981    1
9982    1
9991    1
9997    1
9998    1
Name: Exited, Length: 4076, dtype: int64

In [468]:
X_train, X_test, Y_train, Y_test = train_test_split(x , y , test_size = 0.2, stratify=y, random_state=2)

In [469]:
print(x.shape, X_train.shape, X_test.shape)

(4076, 13) (3260, 13) (816, 13)


**Logistic Regression Model**

In [471]:
model = LogisticRegression()

In [472]:
model.fit(X_train, Y_train)

LogisticRegression()

**Model Evaluation**

In [474]:
preditions = model.predict(X_test)
preditions

array([0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,

In [475]:
X_train.head(1)

CreditScore  Gender  Age  Tenure  Balance  NumOfProducts  HasCrCard  \
4548          635       2   58       1      0.0              1          1   

      IsActiveMember  EstimatedSalary  Complain  Satisfaction Score  \
4548               1         58907.08         1                   1   

      Card Type  Point Earned  
4548          4           318

In [476]:
input_data_model = pd.DataFrame(
    [[530,2,38,4,12000,1,1,1,249467,1,1,3,420]],
    columns=['CreditScore','Gender','Age','Tenure','Balance','NumOfProducts','HasCrCard','IsActiveMember','EstimatedSalary','Complain','Satisfaction Score','Card Type','Point Earned'])

In [477]:
input_data_model

CreditScore  Gender  Age  Tenure  Balance  NumOfProducts  HasCrCard  \
0          530       2   38       4    12000              1          1   

   IsActiveMember  EstimatedSalary  Complain  Satisfaction Score  Card Type  \
0               1           249467         1                   1          3   

   Point Earned  
0           420

In [478]:
predition = model.predict(input_data_model)
predition

array([1], dtype=int64)

**Accuracy on training data**

In [480]:
X_train_prediction = model.predict(X_train)
accuracy = accuracy_score(X_train_prediction, Y_train)
print("Accuracy on Training data : ", accuracy)

Accuracy on Training data :  0.7619631901840491


**Accuracy on test data**

In [482]:
X_test_prediction = model.predict(X_test)
test_accuracy = accuracy_score(X_test_prediction, Y_test)
print("Accuracy on Testing data : ", test_accuracy)

Accuracy on Testing data :  0.7450980392156863


**Decision Tree Model**

In [484]:
Random = RandomForestClassifier()

In [485]:
Random.fit(X_train, Y_train)

RandomForestClassifier()

In [486]:
predits = Random.predict(X_test)
predits

array([1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,

In [487]:
X_train.head(1)

CreditScore  Gender  Age  Tenure  Balance  NumOfProducts  HasCrCard  \
4548          635       2   58       1      0.0              1          1   

      IsActiveMember  EstimatedSalary  Complain  Satisfaction Score  \
4548               1         58907.08         1                   1   

      Card Type  Point Earned  
4548          4           318

In [488]:
input_data = pd.DataFrame(
    [[530,1,38,4,12000,1,1,1,249467,1,1,3,420]],
    columns=['CreditScore','Gender','Age','Tenure','Balance','NumOfProducts','HasCrCard','IsActiveMember','EstimatedSalary','Complain','Satisfaction Score','Card Type','Point Earned'])

In [489]:
input_data

CreditScore  Gender  Age  Tenure  Balance  NumOfProducts  HasCrCard  \
0          530       1   38       4    12000              1          1   

   IsActiveMember  EstimatedSalary  Complain  Satisfaction Score  Card Type  \
0               1           249467         1                   1          3   

   Point Earned  
0           420

In [490]:
predit = Random.predict(input_data)
predit

array([1], dtype=int64)

**Accuracy on training data**

In [492]:
X_train_predict = Random.predict(X_train)
accuracy = accuracy_score(X_train_predict, Y_train)
print("Accuracy on Training data : ", accuracy)

Accuracy on Training data :  1.0


**Accuracy on test data**

In [494]:
X_test_predict = Random.predict(X_test)
test_accuracy = accuracy_score(X_test_predict, Y_test)
print("Accuracy on Testing data : ", test_accuracy)

Accuracy on Testing data :  0.9987745098039216


**CONCLUSION**

**Random Forest Classifier model is more accurate because it has 100% accuracy on training data and 99% accuracy on testing data, which is much better than Logistic Regression Model**

**Serialization(for easier deployment)**

In [498]:
import pickle
pickle_out = open("Random.pkl", "wb")
pickle.dump(Random,pickle_out)
pickle_out.close()